services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  test-app-backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.httpbackend
    ports:
      - 8081:8081
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres
    depends_on:
      - postgres

  test-app-websocket:
    build:
      context: .
      dockerfile: docker/Dockerfile.wsbackend
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres
    depends_on:
      - postgres

  test-app-frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
      args:
        - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres
    depends_on:
      - postgres

volumes:
  postgres_data: