services:
  postgres:
    image: postgres

    environment:
      - POSTGRES_PASSWORD=mysecretpassword

    ports:
      - 5432:5432

    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.httpbackend

    container_name: test-app-backend

    ports:
      - 8081:8081

    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres

    depends_on:
      - postgres

  websocket:
    build:
      context: .
      dockerfile: docker/Dockerfile.wsbackend

    container_name: test-app-websocket

    ports:
      - 8080:8080

    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres

    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend

    container_name: test-app-frontend

    ports:
      - 3000:3000

    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres
      
    depends_on:
      - postgres

volumes:
  postgres_data: