name: Deploy websocket
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Image build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.wsbackend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/test-app-websocket:${{ github.sha }}
          
  